# apiVersion: apps/v1
# kind: Deployment
# metadata:
#    name: app
# spec:
#     replicas: 1
#     selector:
#         matchLabels:
#             app: app
#    template:
#      metadata:
#        labels:
#          app: app
#      spec:
#        containers:
#        - name: app
#          image: jp.icr.io/petnamespace2/app
#          imagePullPolicy: Always
#          ports:
#          - containerPort: 5000

 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: app
 spec:
   replicas: 1
   selector:
     matchLabels:
       app: app
   template:
     metadata:
       labels:
         app: app
     spec:
       containers:
       - name: app
         image: jp.icr.io/mine/app
         imagePullPolicy: Always
         ports:
         - containerPort: 5000